CREATE DATABASE catalog;

CREATE TABLE
    genres (
        id SERIAL PRIMARY KEY,
        name VARCHAR(100) NOT NULL
    );

CREATE TABLE
    music_albums (
        id SERIAL PRIMARY KEY,
        title VARCHAR(100) NOT NULL,
        genre_id INTEGER NOT NULL,
        author_id INTEGER NOT NULL,
        label_id INTEGER NOT NULL,
        publish_date DATE NOT NULL,
        archived BOOLEAN NOT NULL,
        on_spotify BOOLEAN NOT NULL,
        FOREIGN KEY (genre_id) REFERENCES genre (id) ON DELETE CASCADE
    );

CREATE TABLE
    labels (
        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        title VARCHAR(100) NOT NULL,
        color VARCHAR(100) NOT NULL
    );

CREATE TABLE
    books (
        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        title VARCHAR(100) NOT NULL,
        publisher VARCHAR(100) NOT NULL,
        publish_date DATE NOT NULL,
        cover_state VARCHAR(100) NOT NULL,
        archived BOOLEAN NOT NULL,
        genre_id INTEGER NOT NULL,
        author_id INTEGER NOT NULL,
        label_id INTEGER NOT NULL,
        FOREIGN KEY (label_id) REFERENCES labels(id) ON DELETE CASCADE
    );

CREATE TABLE
    authors(
        id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
        first_name VARCHAR(100),
        last_name VARCHAR(100)
    );

CREATE TABLE
    games(
        id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
        title VARCHAR(100),
        publish_date DATE,
        archived BOOLEAN,
        multiplayer BOOLEAN,
        last_played_at DATE,
        author_id INT REFERENCES authors(id)
    );
